import { Button , ComboBox} from "std-widgets.slint";

component MyLabel inherits HorizontalLayout {
  in property <string> text;

  padding: 15px;
  Text {
    text: text;
    horizontal-alignment: right;
    vertical-alignment: center;
  }
}

export component MainWindow {
  callback input_path_button_clicked();
  callback output_path_button_clicked();
  callback calculate_button_clicked();

  in-out property <string> error-message;
  in-out property <string> input-path;
  in-out property <string> output-path;
  in-out property <bool> buttons-enabled: true;

  VerticalLayout {
    padding: 20px;

    Text {
      text: "Recursive Hash Calculator";
      horizontal-alignment: center;
      font-weight: 600;
      font-size: 16px;
      padding-bottom: 20px;
    }

    GridLayout {
      padding-bottom: 20px;

      Row {
        MyLabel { text: "Calculate Hashes For"; }
        Button {
          text: "Open Directory";
          enabled: root.buttons-enabled;
          clicked => { root.input_path_button_clicked() }
        }
      }

      Row {
        MyLabel { text: "Save CSV Output To"; }
        Button {
          text: "Open Directory";
          enabled: root.buttons-enabled;
          clicked => { root.output_path_button_clicked() }
        }
      }
    }

    if (error-message != "") : Text {
      text: error-message;
      font-size: 14px;
      color: red;
      horizontal-alignment: center;
      vertical-alignment: center;
    }

    Button {
      text: "Calculate";
      enabled: root.buttons-enabled;
      clicked => { root.calculate_button_clicked() }
    }
  }
}