import { Button , ComboBox , VerticalBox} from "std-widgets.slint";
import { InfoText } from "components/info_text.slint";
import { GridLabel } from "components/grid_label.slint";
import { GridButton } from "components/grid_button.slint";
import { PathLabel } from "components/path_label.slint";

export component MainWindow inherits Window {
  callback input_path_button_clicked();
  callback output_path_button_clicked();
  callback calculate_button_clicked();

  in-out property <string> input-path;
  in-out property <string> output-path;

  in-out property <bool> buttons-enabled: true;

  in-out property <string> info-message;
  in-out property <string> error-message;

  title: "Recursive Hash Calculator";

  VerticalLayout {
    padding: 20px;
    alignment: center;

    HorizontalLayout {
      alignment: center;
      padding-bottom: 10px;

      GridLabel { text: "Calculate Hashes For"; }
      VerticalLayout {
        GridButton {
          text: "Open Directory";
          enabled: root.buttons-enabled;
          clicked => { root.input_path_button_clicked() }
        }
        if (input-path != "") : PathLabel {
          text: input-path;
        }
      }
    }

    HorizontalLayout {
      alignment: center;
      padding-bottom: 20px;

      GridLabel { text: "Save CSV Output To"; }
      VerticalLayout {
        GridButton {
          text: "Open Directory";
          enabled: root.buttons-enabled;
          clicked => { root.output_path_button_clicked() }
        }
        if (output-path != "") : PathLabel {
          text: output-path;
        }
      }
    }

    if (info-message != "") : InfoText {
      text: info-message;
    }

    if (error-message != "") : InfoText {
      text: error-message;
      color: red;
    }

    HorizontalLayout {
      alignment: center;

      Button {
        text: "Calculate";
        enabled: root.buttons-enabled;
        clicked => { root.calculate_button_clicked() }
        height: 48px;
        width: 340px;
      }
    }
  }
}
